#!/usr/bin/env bash

# Running ./setup creates links in the
# qmk_firmware directory keymaps or keyboards
# folders so that we can keep custom keymaps/boards
# under separate version control, while pulling changes
# from QMK itself.
#
# Build keymap for 3x5 ferris sweep with:
# qmk compile -kb ferris/sweep -km mini3x5

MY_HOME=`echo $HOME`
QMK_HOME="$MY_HOME/qmk_firmware"

# Gets the full path to this keymaps repo's directory
REPO_DIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"

function symlink_mini3x5_custom_keymap() {
  local source_keymap="$REPO_DIR/mini3x5"
  local symlink_destination="$QMK_HOME/keyboards/ferris/keymaps/mini3x5"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking Ferris mini3x5 keymap"
    ln -s "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
}

symlink_mini3x5_custom_keymap
